### ISSUE TITLE
MD5 stuff breaking new projects

### ISSUE THREAD

**Issue by Frozenfire92** [Exelord/ember-initials#25]
I've been using v2.4.0 on an existing project. Starting a new project the md5 stuff you recently added has broken it

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '.../tmp/source_map_concat-input_base_path-SVHjchpq.tmp/bower_components/blueimp-md5/js/md5.min.js' 
```

After digging around it seems related to https://github.com/ember-cli/ember-cli/issues/2912

**Comment by Frozenfire92** [comment]
happened on both 3.0.2 (when I started project) and 3.0.3

**Comment by Frozenfire92** [comment]
maybe relevant ember info

```
ember -v
ember-cli: 2.11.0
node: 4.7.3
os: linux x64
```

**Comment by Exelord** [comment]
Related to #22 
If you upgrading from 3.0.0 and up to 3.0.3 please run `ember generate ember-initials` it should solve the problem with bower dependency or remove completly ember-initials from package.json and run `ember install ember-initials`

**Comment by Frozenfire92** [comment]
This didn't happen from an upgrade though, it happened from a fresh installation (and new ember project).

Running `ember generate ember-initials` did fix it, but this shouldn't be needed. Something about the postinstall isn't working correctly

**Comment by Exelord** [comment]
Yep, exactly that behavior is fixed in 3.0.3. You can try to create a new test app by using `ember new test` and install an addon by `ember install ember-initials`- it works as expected.

the problem is only if you installed the package in version 3.0.0 to 3.0.2. Then you have to run this task manually by using `ember generate ember-initials`.

Anyway... big thanks for reporting this and help with resolving. :) Please close this PR if everything is now clear.

**Comment by alechirsch** [comment]
I am still having this issue with a fresh installation. I am trying to use this in another addon, and it is not installing correctly in the consuming application.

**Comment by Exelord** [comment]
OK @alechirsch, so the problem is in addons not in the consuming application. If you want to use any addon with dependency in your addon you have to expose his dependency explicitly. So you have to also add a file: https://github.com/Exelord/ember-initials/blob/master/blueprints/ember-initials/index.js

But to be honest, I'm not sure if adding ember addons to the addon is a good practice. If you just install an addon in your addon it will be accessible in your tests but if you want to use initials in the addon folder you should add a dependency explicitly to users app by using:

```js
this.addAddonToProject('ember-initials');
```

in your blueprint.
